export enum TestStatus {
  NEGATIVE = 'NEGATIVE',
  POSITIVE = 'POSITIVE',
  INPROGRESS = 'INPROGRESS',
  INCONCLUSIVE = 'INCONCLUSIVE',
}

export enum UserStatus {
  GOOD = 'GOOD',
  PENDING = 'PENDING',
  UNTESTED = 'UNTESTED',
  POSITIVE = 'POSITIVE',
}
